analyzer:
# Lint rules and documentation, see http://dart-lang.github.io/linter/lints

# Import pedantic rules
include: package:pedantic/analysis_options.1.7.0.yaml

linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
    - annotate_overrides
