name: imap_client
description: IMAP (version 4rev1) implementation to get emails from an external server
version: 0.2.7
homepage: https://github.com/michaelspiss/imap_client
author: Michael Spiss <michaelspiss.dev@mailbox.org>
documentation:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  logging: ^0.11.3+2
  pedantic: ^1.8.0+1
  utf7: ^0.2.0

dev_dependencies:
  test: ^1.6.10
  mockito: ^4.1.1
