name: ImapClient
description: An interface to get emails via the imap protocol (version 4rev1)
# version: 1.0.0
# homepage: https://github.com/michaelspiss/ImapClient
# author: Michael Spiss <michaelspiss.dev@mailbox.org>

environment:
  sdk: '>=2.0.0-dev.67.0 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.30
